Imports MySql.Data.MySqlClient
Imports CrystalDecisions.CrystalReports.Engine
Public Class frmTiketPrint
    Dim sqlPrint As String = ""
    Public where As String
    Private Sub frmTiketPrint_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        CrystalReportViewer1.ReportSource = Nothing
        CrystalReportViewer1.Refresh()
        'sqlPrint = "SELECT `tiketdtl`.*   , IF(`tiketdtl`.`GoArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`GoArea`)) AS DepartareaName     , IF(`tiketdtl`.`BackArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`BackArea`)) AS ArrivalareaName     , IF(`tiketdtl`.`Country`='','',(SELECT CountryName FROM country WHERE CountryID=`tiketdtl`.`country`)) AS Country     , IF(`tiketdtl`.`AgentID`='','',(SELECT AgentName FROM agent WHERE AgentID=`tiketdtl`.`AgentID`)) AS AgentName     , IF(`tiketdtl`.`GoRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`GoRuteID`)) AS DepartRute     , IF(`tiketdtl`.`BackRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`BackRuteID`)) AS ArrivalRute     , IF(`tiketdtl`.`GoTrip`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`GoTrip`)) AS DepartTrip     , IF(`tiketdtl`.`TripBack`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`TripBack`)) AS ArrivalTrip , IF(`tiketdtl`.`QtyTipe`=1,'Adult',IF(`tiketdtl`.`QtyTipe`=2,'Child','FOC')) AS Age FROM `tiketdtl` where " & where & " Union SELECT `tiketdtl`.*   , IF(`tiketdtl`.`GoArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`GoArea`)) AS DepartareaName     , IF(`tiketdtl`.`BackArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`BackArea`)) AS ArrivalareaName     , IF(`tiketdtl`.`Country`='','',(SELECT CountryName FROM country WHERE CountryID=`tiketdtl`.`country`)) AS Country     , IF(`tiketdtl`.`AgentID`='','',(SELECT AgentName FROM agent WHERE AgentID=`tiketdtl`.`AgentID`)) AS AgentName     , IF(`tiketdtl`.`GoRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`GoRuteID`)) AS DepartRute     , IF(`tiketdtl`.`BackRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`BackRuteID`)) AS ArrivalRute     , IF(`tiketdtl`.`GoTrip`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`GoTrip`)) AS DepartTrip     , IF(`tiketdtl`.`TripBack`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`TripBack`)) AS ArrivalTrip , IF(`tiketdtl`.`QtyTipe`=1,'Adult',IF(`tiketdtl`.`QtyTipe`=2,'Child','FOC')) AS Age FROM `tiketdtl` where " & where & " and Tipe"
        sqlPrint = "SELECT if(`tiketdtl`.Tipe='OW','One-Way Ticket','Return Ticket')as Tipes,`tiketdtl`.NoBook,`tiketdtl`.GOpICKUP AS pICUP,`tiketdtl`.NoEtiket,`tiketdtl`.NoTiket,`tiketdtl`.mrs,`tiketdtl`.Guest,`tiketdtl`.Qty,`tiketdtl`.GoDate   , IF(`tiketdtl`.`GoArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`GoArea`)) AS DepartareaName     , IF(`tiketdtl`.`Country`='','',(SELECT CountryName FROM country WHERE CountryID=`tiketdtl`.`country`)) AS Country     , IF(`tiketdtl`.`AgentID`='','',(SELECT AgentName FROM agent WHERE AgentID=`tiketdtl`.`AgentID`)) AS AgentName     , IF(`tiketdtl`.`GoRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`GoRuteID`)) AS DepartRute     , IF(`tiketdtl`.`GoTrip`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`GoTrip`)) AS DepartTrip      , IF(`tiketdtl`.`QtyTipe`=1,'Adult',IF(`tiketdtl`.`QtyTipe`=2,'Child','FOC')) AS Age FROM `tiketdtl` where (" & where & ") UNION SELECT if(`tiketdtl`.Tipe='OW','One-Way Ticket','Return Ticket') as Tipes, `tiketdtl`.NoBook,`tiketdtl`.BackPickup AS pICUP,`tiketdtl`.NoEtiket,`tiketdtl`.NoTiket,`tiketdtl`.mrs,`tiketdtl`.Guest,`tiketdtl`.Qty,`tiketdtl`.backDate   , IF(`tiketdtl`.`backArea`=0,'',(SELECT AreaName FROM AREA WHERE AreaID=`tiketdtl`.`BackArea`)) AS DepartareaName     , IF(`tiketdtl`.`Country`='','',(SELECT CountryName FROM country WHERE CountryID=`tiketdtl`.`country`)) AS Country     , IF(`tiketdtl`.`AgentID`='','',(SELECT AgentName FROM agent WHERE AgentID=`tiketdtl`.`AgentID`)) AS AgentName     , IF(`tiketdtl`.`BackRuteID`='','',(SELECT RuteName FROM rute WHERE RuteID=`tiketdtl`.`BackRuteID`)) AS DepartRute     , IF(`tiketdtl`.`TripBack`='','',(SELECT TripName FROM trip WHERE tripID=`tiketdtl`.`TripBack`)) AS DepartTrip      , IF(`tiketdtl`.`QtyTipe`=1,'Adult',IF(`tiketdtl`.`QtyTipe`=2,'Child','FOC')) AS Age FROM `tiketdtl` where (" & where & ") AND tiketdtl.Tipe='RT'"
        Dim crp As New PrintTiket
        Call ConnectDatabase()
        Dim da As MySqlDataAdapter
        Dim dt As DataTable
        da = New MySqlDataAdapter(sqlPrint, conn)
        dt = New DataTable
        da.Fill(dt)
        crp.SetDataSource(dt)
        CrystalReportViewer1.ReportSource = crp
        CrystalReportViewer1.Refresh()
    End Sub
End Class